#!/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'opencontrail-kubelet==0.1','console_scripts','opencontrail-kubelet-plugin'
__requires__ = 'opencontrail-kubelet==0.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('opencontrail-kubelet==0.1', 'console_scripts', 'opencontrail-kubelet-plugin')()
    )
